export const CAPTURE_INTERVAL_DEFAULT_MS = 30_000;
export const CAPTURE_INTERVAL_MIN_MS = 5_000;
export const CAPTURE_INTERVAL_MAX_MS = 120_000;

export const FALLBACK_FAIL_THRESHOLD = 5;
export const CAPTURE_MAX_WIDTH = 1920;

export const DHASH_SIZE = 8;
export const HAMMING_THRESHOLD_DEFAULT = 8;
